const Menu = [
    {
      id: 1,
      image: "../images/Exersise/Pushup.gif",
      name: "Push Ups",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15" ,
      rest: "	Rest : 30 Sec" ,
    },
  
    {
      id: 2,
      image: "../images/Exersise/ChestPress.gif",
      name: "Bench Press",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 90 Sec" ,
    },
    {
      id: 3,
      image: "../images/Exersise/inclineCP.gif",
      name: "I-Dumble Press",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 4,
      image: "../images/Exersise/DDumblePress.gif",
      name: "D-DumblePress",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 5,
      image: "../images/Exersise/Fly.gif",
      name: "Dumble Fly",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 6,
      image: "../images/Exersise/Dumbbell-Pullover.gif",
      name: "Pullover",
      type: "Chest",
      category: "MON",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 7,
      image: "../images/Exersise/OverheadPress.gif",
      name: "Overhead Press",
      type: "Shoulder",
      category: "TUE",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 90 Sec" ,
    },
    {
      id: 8,
      image: "../images/Exersise/ShoulderPress.gif",
      name: "Shoulder Press",
      type: "Shoulder",
      category: "TUE",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 9,
      image: "../images/Exersise/Siderais.gif",
      name: "Side rais",
      type: "Shoulder",
      category: "TUE",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 15" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 10,
      image: "../images/Exersise/Frontrais.gif",
      name: "Front rais",
      type: "Shoulder",
      category: "TUE",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 11,
      image: "../images/Exersise/highPull.gif",
      name: "Upright barbell ",
      type: "Shoulder",
      category: "TUE",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 12,
      image: "../images/Exersise/PullUp.gif",
      name: "Pull Up ",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 20, 15, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 12,
      image: "../images/Exersise/Bent-OverRow.gif",
      name: "Bent-Over Row ",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 13,
      image: "../images/Exersise/Widepull.gif",
      name: "Pull-Down ",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 15, 15, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 14,
      image: "../images/Exersise/Dumbbell-Row.gif",
      name: "Dumbbell Row ",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 15,
      image: "../images/Exersise/SCR.gif",
      name: "seat cable row",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 16,
      image: "../images/Exersise/hyperextension.gif",
      name: "Hyperextension",
      type: "Back",
      category: "WED",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 17,
      image: "../images/Exersise/Barbell-Curl.gif",
      name: "Barbell-Curl",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 20, 15, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 18,
      image: "../images/Exersise/Seated-Incline-Dumbbell-Curl.gif",
      name: "Barbell-Curl",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 19,
      image: "../images/Exersise/Preacher-Curl.gif",
      name: "Preacher-Curl",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 20, 15, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 20,
      image: "../images/Exersise/Barbell-Reverse-Curl.gif",
      name: "Reverse Curl",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 21,
      image: "../images/Exersise/Seated-Dumbbell-Triceps-Extension.gif",
      name: "Tricep Ext",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 22,
      image: "../images/Exersise/Pushdown.gif",
      name: "Pushdown",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 23,
      image: "../images/Exersise/One-Arm-Reverse-Push-Down.gif",
      name: "ReversePush",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 24,
      image: "../images/Exersise/Dumbbell-Kickback.gif",
      name: "Kickback",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 25,
      image: "../images/Exersise/barbell-Wrist-Curl.gif",
      name: "Wrist-Curl",
      type: "Arms",
      category: "THU",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 26,
      image: "../images/Exersise/BARBELL-SQUAT.gif",
      name: "Squat",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 90 Sec" ,
    },
    {
      id: 27,
      image: "../images/Exersise/Leg-Press.gif",
      name: "Leg Press",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 90 Sec" ,
    },
    {
      id: 28,
      image: "../images/Exersise/Barbell-Deadlift.gif",
      name: "Deadlift",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 120 Sec" ,
    },
    {
      id: 29,
      image: "../images/Exersise/Leg-Curl.gif",
      name: "Leg Curl",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 30,
      image: "../images/Exersise/LEG-EXTENSION.gif",
      name: "Leg Extension",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 31,
      image: "../images/Exersise/Standing-Calf-Raise.gif",
      name: "Calf",
      type: "Leg",
      category: "FRI",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 12" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 32,
      image: "../images/Exersise/Treadmill.gif",
      name: "Running",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 1" ,
      reps: " Time : 15 Min" ,
      rest: "	Rest : 120 Sec" ,
    },
    {
      id: 33,
      image: "../images/Exersise/Jump-Rope.gif",
      name: "Jump Rope",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Time : 2 Min" ,
      rest: "	Rest : 60 Sec" ,
    },
    {
      id: 34,
      image: "../images/Exersise/Jumping-jack.gif",
      name: "Jumping jack",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Time : 60 Sec" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 35,
      image: "../images/Exersise/High-Knee-Run.gif",
      name: "High Knee Run",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Time : 40 Sec" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 36,
      image: "../images/Exersise/burpees.gif",
      name: "Burpees",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Reps : 15, 12, 10" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 37,
      image: "../images/Exersise/Crunch.gif",
      name: "Crunch",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Reps : 20" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 38,
      image: "../images/Exersise/Lying-Leg.gif",
      name: "Leg Raise",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Reps : 20, 15, 15" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 39,
      image: "../images/Exersise/Seated-Bench-Leg-Pull-in.gif",
      name: "Leg Pull",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 3" ,
      reps: " Reps : 15" ,
      rest: "	Rest : 30 Sec" ,
    },
    {
      id: 40,
      image: "../images/Exersise/plank.png",
      name: "Plank",
      type: "Cardio",
      category: "SAT",
      set: " Sets : 1" ,
      reps: " Time : 60 Sec" ,
      rest: "	Rest : 30 Sec" ,
    },

    {
      id: 41,
      image: "../images/Exersise/Rest.gif",
      name: "Rest",
      type: "Rest",
      category: "SUN",
      set: "#Sleep Can Boost Your Immune System" ,
      reps: "#Sleep is best Medition" ,

    },
    {
      id: 42,
      image: "../images/Exersise/R1.gif",
      name: "Rest",
      type: "Rest",
      category: "SUN",
      set: "#Sleeping Can Increase Productivity" ,
      reps: "#Improved Mental Health" ,
    },
    {
      id: 43,
      image: "../images/Exersise/R3.gif",
      name: "Rest",
      type: "Rest",
      category: "SUN",
      set: "#Can maximize athletic performance" ,
      reps: "#Sleep Sloves Everything" ,
    },
    
  ];
  
  export default Menu;